services:
  mysql:
    build:
      context: mySQL
      args:
        USER: ${CLOUD1_DB_USER}
        PASSWORD: ${CLOUD1_DB_PASSWORD}
        TCP_PORT: ${CLOUD1_DB_TCP_PORT}
        DATABASE: ${CLOUD1_DB_NAME}
        ROOT_PASS: ${CLOUD1_DB_ROOT_PASSWORD}
    volumes:
      - mysql_database:/var/lib/mysql
    restart: always

  phpmyadmin:
    links:
      - mysql
    build:
      context: phpMyAdmin
      args:
        HOST: mysql
        MYSQL_TCP_PORT: ${CLOUD1_DB_TCP_PORT}
    depends_on:
      - mysql
    ports:
      - 8080:80
    restart: always

  wordpress:
    links:
      - mysql
    build:
      context: wordpress
      args:
        DB_HOST: mysql:${CLOUD1_DB_TCP_PORT}
        DB_USER: ${CLOUD1_DB_USER}
        DB_PASSWORD: ${CLOUD1_DB_PASSWORD}
        DB_NAME: ${CLOUD1_DB_NAME}
    volumes:
      - wordpress:/var/www/html
    restart: always
    ports:
      - 8081:80
    depends_on:
      - mysql

volumes:
  wordpress:
  mysql_database: